#pragma checksum "..\..\..\..\User\UICommand.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "01944F28765F75F7DC2331D83BEE6F7C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace ExtensibleStorageManager {
    
    
    /// <summary>
    /// UICommand
    /// </summary>
    public partial class UICommand : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 14 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label m_label_applicationAppId;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label m_textBox_SchemaPath;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox m_textBox_SchemaId;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_NewSchemaId;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox m_textBox_SchemaName;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox m_textBox_SchemaDocumentation;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox m_textBox_SchemaVendorId;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox m_textBox_SchemaApplicationId;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton m_rb_ReadAccess_Application;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton m_rb_ReadAccess_Public;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton m_rb_ReadAccess_Vendor;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton m_rb_WriteAccess_Application;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton m_rb_WriteAccess_Public;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton m_rb_WriteAccess_Vendor;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_CreateSetSave_Simple;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_EditExisting_Simple;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_CreateSetSave_Complex;
        
        #line default
        #line hidden
        
        
        #line 122 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_LookupExtract;
        
        #line default
        #line hidden
        
        
        #line 123 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_CreateWrapperFromSchema;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\..\User\UICommand.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button m_button_CreateSchemaFromXml;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/ExtensibleStorageManager;component/user/uicommand.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\User\UICommand.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.m_label_applicationAppId = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.m_textBox_SchemaPath = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.m_textBox_SchemaId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.m_button_NewSchemaId = ((System.Windows.Controls.Button)(target));
            
            #line 35 "..\..\..\..\User\UICommand.xaml"
            this.m_button_NewSchemaId.Click += new System.Windows.RoutedEventHandler(this.m_button_NewSchemaId_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.m_textBox_SchemaName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.m_textBox_SchemaDocumentation = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.m_textBox_SchemaVendorId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.m_textBox_SchemaApplicationId = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.m_rb_ReadAccess_Application = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 10:
            this.m_rb_ReadAccess_Public = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 11:
            this.m_rb_ReadAccess_Vendor = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 12:
            this.m_rb_WriteAccess_Application = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 13:
            this.m_rb_WriteAccess_Public = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 14:
            this.m_rb_WriteAccess_Vendor = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 15:
            this.m_button_CreateSetSave_Simple = ((System.Windows.Controls.Button)(target));
            
            #line 115 "..\..\..\..\User\UICommand.xaml"
            this.m_button_CreateSetSave_Simple.Click += new System.Windows.RoutedEventHandler(this.m_button_CreateSetSaveSimple_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.m_button_EditExisting_Simple = ((System.Windows.Controls.Button)(target));
            
            #line 116 "..\..\..\..\User\UICommand.xaml"
            this.m_button_EditExisting_Simple.Click += new System.Windows.RoutedEventHandler(this.m_button_EditExistingSimple_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.m_button_CreateSetSave_Complex = ((System.Windows.Controls.Button)(target));
            
            #line 118 "..\..\..\..\User\UICommand.xaml"
            this.m_button_CreateSetSave_Complex.Click += new System.Windows.RoutedEventHandler(this.m_button_CreateSetSaveComplex_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.m_button_LookupExtract = ((System.Windows.Controls.Button)(target));
            
            #line 122 "..\..\..\..\User\UICommand.xaml"
            this.m_button_LookupExtract.Click += new System.Windows.RoutedEventHandler(this.m_button_LookupExtract_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.m_button_CreateWrapperFromSchema = ((System.Windows.Controls.Button)(target));
            
            #line 123 "..\..\..\..\User\UICommand.xaml"
            this.m_button_CreateWrapperFromSchema.Click += new System.Windows.RoutedEventHandler(this.m_button_CreateWrapperFromSchema_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.m_button_CreateSchemaFromXml = ((System.Windows.Controls.Button)(target));
            
            #line 124 "..\..\..\..\User\UICommand.xaml"
            this.m_button_CreateSchemaFromXml.Click += new System.Windows.RoutedEventHandler(this.m_button_CreateSchemaFromXml_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

