#pragma checksum "..\..\..\..\OptionsDialog\UserControl2.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "7B0ED3B97AF20C2668E65D1F8EE493BC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Revit.SDK.Samples.UIAPI.CS {
    
    
    /// <summary>
    /// UserControl2
    /// </summary>
    public partial class UserControl2 : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel stackPanel1;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox1;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid1;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox1;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox2;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox3;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock3;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox2;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid2;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock4;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox1;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock5;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox2;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox3;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid3;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock6;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox3;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock7;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox4;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox4;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid4;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox4;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock8;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox5;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid5;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox5;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock9;
        
        #line default
        #line hidden
        
        
        #line 110 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock10;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Slider slider1;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock11;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock12;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox1;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox6;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid6;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox6;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock13;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox groupBox7;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid7;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox checkBox7;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\..\OptionsDialog\UserControl2.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock14;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/UIAPI;component/optionsdialog/usercontrol2.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\OptionsDialog\UserControl2.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.stackPanel1 = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 2:
            this.groupBox1 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 3:
            this.grid1 = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.checkBox1 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 5:
            this.checkBox2 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.checkBox3 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.textBlock3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.groupBox2 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 11:
            this.grid2 = ((System.Windows.Controls.Grid)(target));
            return;
            case 12:
            this.textBlock4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.comboBox1 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.textBlock5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.comboBox2 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.groupBox3 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 17:
            this.grid3 = ((System.Windows.Controls.Grid)(target));
            return;
            case 18:
            this.textBlock6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.comboBox3 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 20:
            this.textBlock7 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.comboBox4 = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 22:
            this.groupBox4 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 23:
            this.grid4 = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            this.checkBox4 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.textBlock8 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            this.groupBox5 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 27:
            this.grid5 = ((System.Windows.Controls.Grid)(target));
            return;
            case 28:
            this.checkBox5 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 29:
            this.textBlock9 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 30:
            this.textBlock10 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 31:
            this.slider1 = ((System.Windows.Controls.Slider)(target));
            return;
            case 32:
            this.textBlock11 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 33:
            this.textBlock12 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.textBox1 = ((System.Windows.Controls.TextBox)(target));
            return;
            case 35:
            this.groupBox6 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 36:
            this.grid6 = ((System.Windows.Controls.Grid)(target));
            return;
            case 37:
            this.checkBox6 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 38:
            this.textBlock13 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.groupBox7 = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 40:
            this.grid7 = ((System.Windows.Controls.Grid)(target));
            return;
            case 41:
            this.checkBox7 = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 42:
            this.textBlock14 = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

