#pragma checksum "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "84439D34B66E1BD86D123F6742D9BAAF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Revit.SDK.Samples.DockableDialogs.CS {
    
    
    /// <summary>
    /// DockingSetupDialog
    /// </summary>
    public partial class DockingSetupDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 14 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_newGuid;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_left;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_right;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_top;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_bottom;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox tb_targetGuid;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_ElementView;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_HostByLinkNavigator;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_ProjectBrowser;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_PropertiesPalette;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_RebarBrowser;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_SystemNav;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_Null;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_top;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_left;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_right;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_bottom;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_tabbed;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton rb_floating;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_ok;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/DockableDialogs;component/dockingsetupdialog/dockingsetupdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.tb_newGuid = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.tb_left = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.tb_right = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.tb_top = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.tb_bottom = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.tb_targetGuid = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.rb_ElementView = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 8:
            this.rb_HostByLinkNavigator = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 9:
            this.rb_ProjectBrowser = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 10:
            this.rb_PropertiesPalette = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 11:
            this.rb_RebarBrowser = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 12:
            this.rb_SystemNav = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 13:
            this.rb_Null = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 14:
            this.rb_top = ((System.Windows.Controls.RadioButton)(target));
            
            #line 46 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.rb_top.Checked += new System.Windows.RoutedEventHandler(this.rb_top_Checked);
            
            #line default
            #line hidden
            return;
            case 15:
            this.rb_left = ((System.Windows.Controls.RadioButton)(target));
            
            #line 47 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.rb_left.Checked += new System.Windows.RoutedEventHandler(this.rb_left_Checked);
            
            #line default
            #line hidden
            return;
            case 16:
            this.rb_right = ((System.Windows.Controls.RadioButton)(target));
            
            #line 48 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.rb_right.Checked += new System.Windows.RoutedEventHandler(this.rb_right_Checked);
            
            #line default
            #line hidden
            return;
            case 17:
            this.rb_bottom = ((System.Windows.Controls.RadioButton)(target));
            
            #line 49 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.rb_bottom.Checked += new System.Windows.RoutedEventHandler(this.rb_bottom_Checked);
            
            #line default
            #line hidden
            return;
            case 18:
            this.rb_tabbed = ((System.Windows.Controls.RadioButton)(target));
            
            #line 51 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.rb_tabbed.Checked += new System.Windows.RoutedEventHandler(this.rb_tabbed_Checked);
            
            #line default
            #line hidden
            return;
            case 19:
            this.rb_floating = ((System.Windows.Controls.RadioButton)(target));
            
            #line 52 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.rb_floating.Checked += new System.Windows.RoutedEventHandler(this.rb_floating_Checked);
            
            #line default
            #line hidden
            return;
            case 20:
            this.btn_ok = ((System.Windows.Controls.Button)(target));
            
            #line 54 "..\..\..\..\DockingSetupDialog\DockingSetupDialog.xaml"
            this.btn_ok.Click += new System.Windows.RoutedEventHandler(this.btn_ok_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

