#pragma checksum "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "2D30E022AFE627F5E49EF48D2A964962"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace Revit.SDK.Samples.RoutingPreferenceTools.CS {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_SelectPipeType;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox_PipeTypes;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button button_CheckWarnings;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button button_CheckSpecificSize;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox comboBox_Sizes;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label label_Warnings;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox textBox_output;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RoutingPreferenceTools;component/routingpreferenceanalysis/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.label_SelectPipeType = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.comboBox_PipeTypes = ((System.Windows.Controls.ComboBox)(target));
            
            #line 24 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
            this.comboBox_PipeTypes.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.comboBox_PipeTypes_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.button_CheckWarnings = ((System.Windows.Controls.Button)(target));
            
            #line 25 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
            this.button_CheckWarnings.Click += new System.Windows.RoutedEventHandler(this.button_CheckWarnings_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.button_CheckSpecificSize = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\RoutingPreferenceAnalysis\MainWindow.xaml"
            this.button_CheckSpecificSize.Click += new System.Windows.RoutedEventHandler(this.button_CheckSpecificSize_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.comboBox_Sizes = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.label_Warnings = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.textBox_output = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

